### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by hjfitz** [itsoc-uop/site#3]
Functioality for setting up events

**Comment by hjfitz** [comment]
Ensure authenticated

Enable saving of following event attributes:

name
time
location

**Comment by SamStenton** [comment]
🌮

**Comment by hjfitz** [comment]
@SamStenton 🌮

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
